apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 882961514310.dkr.ecr.ap-south-1.amazonaws.com/react-node-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: database-1.cr0840yoiitd.ap-south-1.rds.amazonaws.com
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: aitglobal007
            - name: DB_NAME
              value: appdb
