name: CI/CD to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    env:
      AWS_REGION: ap-south-1
      EKS_CLUSTER_NAME: react-node-cluster
      BACKEND_IMAGE: 882961514310.dkr.ecr.ap-south-1.amazonaws.com/react-node-backend
      FRONTEND_IMAGE: 882961514310.dkr.ecr.ap-south-1.amazonaws.com/react-node-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin 882961514310.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push Backend Image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest $BACKEND_IMAGE:latest

   #   - name: Trivy Scan Backend Image (SARIF)
   #     uses: aquasecurity/trivy-action@master
   #     with:
   #       image-ref: backend
   #       format: sarif
   #       output: trivy-backend.sarif
   #       exit-code: 0
   #       severity: LOW

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Trivy Scan Backend to Text File (LOW only)
        run: |
          trivy image --severity LOW \
          --format table \
          --exit-code 0 \
          --output trivy-backend.txt \
          backend
      
      - name: Upload Trivy Text Report (Backend)
        uses: actions/upload-artifact@v4
        with:
          name: trivy-backend-report
          path: trivy-backend.txt
   
      - name: Push image
        run: |
          docker push $BACKEND_IMAGE:latest


      - name: Build and Push Frontend Image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest $FRONTEND_IMAGE:latest
          docker push $FRONTEND_IMAGE:latest

      - name: Update kubeconfig
        run: |
          aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment backend
          kubectl rollout restart deployment frontend
