name: Build and Deploy to EKS

on:
  push:
    branches:
      - master  # or main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  BACKEND_IMAGE: 882961514310.dkr.ecr.ap-south-1.amazonaws.com/react-node-backend
  FRONTEND_IMAGE: 882961514310.dkr.ecr.ap-south-1.amazonaws.com/react-node-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin 882961514310.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build and Push Backend Image
      run: |
        docker build -t backend ./backend
        docker tag backend:latest $BACKEND_IMAGE:latest
        docker push $BACKEND_IMAGE:latest

    - name: Build and Push Frontend Image
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest $FRONTEND_IMAGE:latest
        docker push $FRONTEND_IMAGE:latest

    - name: Update kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/
